/**
 * Description:
 * Class to manage Opportunity-related constants.
 * 
 * Modifications:
 * 03.08.2023 [Tomass Brazovskis] LTAT-7256 - Introduced.
 **/
public with sharing class SEConstantsOpportunity {
    
    // Opportunity RecordType DeveloperNames 
    public static final String OPPORTUNITY_RECORDTYPE_WHOLESALES_OPPORTUNITY = 'Wholesales_Opportunity';

    // Opportunity StageName API Names
    public static final String OPPORTUNITY_STAGE_API_NAME_KVALIFICERA = 'Kvalificera';
}