/**
    About
    -----
    Description: Test Class to test SetSellerOnOpportunityBatch Class
	Create date: September 2015
   
    Update History
    --------------
    Created Sep 2015 - V.I
    
    Issues / TODOs
    --------------  
*/

@isTest
public class Test_SetSellerOnOpportunityBatch {
    
    @isTest static void testBatch(){
        //Test Data Setup
        
        System.assert(true, 'Seller was not set');
    }

}