name: Merge XML Files

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'


    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
          python-version: '3.11.0'
   
      
    - name: Merge XML files
      run: |
        if [ -f "manifest/merged.xml" ];  then
           git config --global user.email "suni9636@gmail.com"
           git config --global user.name "Deadpool"
           git rm mergedfile.xml
           git commit -m 'removed mergedfile'
           git push
        else 
           echo "no merged file"
        fi
        echo "<?xml version="1.0" encoding="UTF-8" ?>" > manifest/merged.xml
        echo "<Package xmlns="http://soap.sforce.com/2006/04/metadata">" >> manifest/merged.xml
        git fetch --all
        for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); 
        do
           if [[ $branch == "dev"* ]]; then
             git checkout $branch
             cp manifest/feature_package.xml p2.xml
             head -n $(($(wc -l < p2.xml) - 2)) p2.xml | tail -n +3 > temp.xml && mv temp.xml p2.xml
             cat p2.xml >>manifest/merged.xml
             echo "" >> manifest/merged.xml
           fi
        done
        echo "</Package>" >> manifest/merged.xml
        #perl -ne 'print if !$seen{$_}++  || /<types>/ || /<\/types>/'  mergedfile.xml > package.xml
        python3 manifest/Merger.py manifest/merged.xml        
        git checkout master
        git config --global user.email "suni9636@gmail.com"
        git config --global user.name "Deadpool"
        git add  manifest/merged.xml
        git commit -m "merged package xml"
        git push origin master
    
