name: Merge XML Files

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge XML files
      run: |
        # Merge XML files using a tool like `xmlstarlet`
        # Replace the commands below with the appropriate merging tool and commands
        # Install xmlstarlet if not available
        sudo apt-get update
        echo "test121313"
        # Merge XML files from branches starting with 'feature' into merged.xml
        for branch in $(git branch --list dev*)
        do
           git checkout $branch
           echo "test1"
        done
      
