name: Merge XML Files

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'
   
      
    - name: Merge XML files
      run: |
        echo "<?xml version="1.0" encoding="UTF-8" ?>" > mergedfile.xml
        echo "<Package xmlns="http://soap.sforce.com/2006/04/metadata">" >> mergedfile.xml
        git fetch --all
        for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); 
        do
           if [[ $branch == "dev"* ]]; then
             echo "test1"
             git checkout $branch
             cp manifest/feature_package.xml p2.xml
             head -n $(($(wc -l < p2.xml) - 2)) p2.xml | tail -n +3 > temp.xml && mv temp.xml p2.xml
             cat p2.xml >>mergedfile.xml
             echo "" >> mergedfile.xml
           fi
        done
        echo "</Package>" >> mergedfile.xml
        #perl -ne 'print if !$seen{$_}++  || /<types>/ || /<\/types>/'  mergedfile.xml > package.xml
        cat mergedfile.xml
        git checkout master
        git config --global user.email "suni9636@gmail.com"
        git config --global user.name "Deadpool"
        git add mergedfile.xml
        git commit -m "merged package xml"
        git push origin master
    
