name: Merge XML Files

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'
   
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet
      
    - name: Merge XML files
      run: |
        echo "test121313"
        echo mergedfile.xml
        git fetch --all
        for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); 
        do
           if [[ $branch == "dev"* ]]; then
             git checkout $branch
             cat manifest/package.xml >> mergedfile.xml
             echo "" >> mergedfile.xml
           fi
        done
        #echo "</root>" >> mergedfile.xml
        cat mergedfile.xml 
    - name: Commit and push changes
      run: |
       git config --global user.email "suni9636@gmail.com"
       git config --global user.name "Deadpool"
       git add mergedfile.xml
       git commit -m "merged package xml"
       git push
