name: Merge XML Files

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests library
      run: pip install requests
      
    - name: Merge XML files
      run: |
        echo "test121313"
        git fetch --all
        for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
          echo "Found branch: $branch"
          git checkout $branch
          echo "reading data"
          cat manifest/package.xml
        done
        echo "test12"

    - name: Commit and push changes
      run: |
       git config --global user.email "suni9636@gmail.com"
       git config --global user.name "Deadpool"
       git add merged_file.xml
       git commit -m "merged package xml"
       git push
