name: sfimerge

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'


    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
          python-version: '3.11.0'
   
      
    - name: Merge files
      run: |  
        nodeOutput=$(node manifest/sfifeatureymlhandler.js)
        echo -e "$nodeOutput">> manifest/sfi_feature_deployment.txt
        mkdir SFIDatapacks
        file_path=manifest/sfi_feature_deployment.txt
        #fetch required data from SFI folder
        if [ ! -f "$file_path" ]; then
          echo "File not found!"
          exit 1
        fi
        while IFS= read -r line; do
             echo "$line"
             substring=$(echo "$line" | awk -F'/' '{print $3}')
             echo "$substring"
             abpath=$(echo "$line" | awk -F'/' '{print $3"/"$4}')
             relpath=SFIDatapacks/"$abpath"
             dirpath=$(echo "$relpath" | awk -F'/' '{print $1"/"$2}')
             mkdir -p  "$dirpath"
             cp -rp "$line" "$relpath"
         done < "$file_path"
         
        git config --global user.email "gitbot@github.com"
        git config --global user.name "gitbot"
        git add  SFIDatapacks
        git commit -m "merged package xml"
        git push -f origin master


        
