name: Merge Vlocity yaml

on:
   workflow_dispatch: 

jobs:
  merge_xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'master'


    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
          python-version: '3.11.0'
   
      
    - name: Merge files
      run: |
        if [ -f "manifest/vlocitymerged.yaml" ];  then
           git config --global user.email "gitbot@github.com"
           git config --global user.name "gitbot"
           git rm manifest/vlocitymerged.yaml
           git commit -m 'removed mergedfile'
           git push -f 
        else 
           echo "no merged file"
        fi
        echo "projectPath: ./vlocity" > manifest/vlocitymerged.yaml
        echo "queries:" >> manifest/vlocitymerged.yaml
        git fetch --all
        for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); 
        do
           if [[ $branch == "dev"* ]]; then
             git checkout $branch
             cp test/feature.yaml p2.yaml
             #head -n $(($(wc -l < p2.yaml) - 3)) p2.yaml > temp.yaml && mv temp.yaml p2.yaml
             head -n $(($(wc -l < p2.yaml) - 3)) p2.yaml | tail -n +3 > temp.yaml && mv temp.yaml p2.yaml
             cat p2.yaml >>manifest/vlocitymerged.yaml
           fi
        done

        git checkout master
        mkdir SFIDatapacks
        file_path=manifest/sficonsolidated.txt
        if [ ! -f "$file_path" ]; then
          echo "File not found!"
          exit 1
        fi
        while IFS= read -r line; do
             echo "$line"
             substring="${line##*/}"
             echo "$substring"
             if [ $substring == "IntegrationProcedure" ];
             then
                cp -rp "$line" SFIDatapacks/IntegrationProcedure
             fi
             elif [ $substring == "DataRaptor" ];
             then
                cp -rp "$line" SFIDatapacks/DataRaptor
             fi
         done < "$file_path"
        
        git config --global user.email "gitbot@github.com"
        git config --global user.name "gitbot"
        git add  SFIDatapacks
        git commit -m "merged package xml"
        git push -f origin master
